AddCSLuaFile()

ENT.Voices = {
	["Grunt"] = {
["OnIdle"] = { "halo_reach/dialog/combat/grunt1/08_idle/idle/idle_1.ogg", "halo_reach/dialog/combat/grunt1/08_idle/idle/idle_2.ogg",
			"halo_reach/dialog/combat/grunt1/08_idle/idle/idle_3.ogg", "halo_reach/dialog/combat/grunt1/08_idle/idle/idle_4.ogg",
			"halo_reach/dialog/combat/grunt1/08_idle/idle/idle_5.ogg", "halo_reach/dialog/combat/grunt1/08_idle/idle/idle_6.ogg",
			"halo_reach/dialog/combat/grunt1/08_idle/idle/idle_7.ogg", "halo_reach/dialog/combat/grunt1/08_idle/idle/idle_8.ogg",
			"halo_reach/dialog/combat/grunt1/08_idle/idle/idle_10.ogg", "halo_reach/dialog/combat/grunt1/08_idle/idle/idle_11.ogg",
			"halo_reach/dialog/combat/grunt1/08_idle/idle/idle_12.ogg" },
["OnAlert"] = { "halo_reach/dialog/combat/grunt1/01_contact/seefoe/seefoe_1.ogg", "halo_reach/dialog/combat/grunt1/01_contact/seefoe/seefoe_2.ogg",
				"halo_reach/dialog/combat/grunt1/01_contact/seefoe/seefoe_3.ogg", "halo_reach/dialog/combat/grunt1/01_contact/seefoe/seefoe_4.ogg",
				"halo_reach/dialog/combat/grunt1/01_contact/seefoe/seefoe_6.ogg", "halo_reach/dialog/combat/grunt1/01_contact/seefoe/seefoe_7.ogg",
				"halo_reach/dialog/combat/grunt1/01_contact/seefoe/seefoe_8.ogg", "halo_reach/dialog/combat/grunt1/01_contact/seefoe/seefoe_9.ogg",
				"halo_reach/dialog/combat/grunt1/01_contact/seefoe/seefoe_10.ogg", "halo_reach/dialog/combat/grunt1/01_contact/seefoe/seefoe_11.ogg",
				"halo_reach/dialog/combat/grunt1/01_contact/seefoe/seefoe_12.ogg", "halo_reach/dialog/combat/grunt1/01_contact/seefoe/seefoe_13.ogg",
				"halo_reach/dialog/combat/grunt1/01_contact/seefoe/seefoe_14.ogg" },
["OnAlertMoreFoes"] = { "halo_reach/dialog/combat/grunt1/01_contact/morefoe/morefoe_1.ogg", "halo_reach/dialog/combat/grunt1/01_contact/morefoe/morefoe_2.ogg",
						"halo_reach/dialog/combat/grunt1/01_contact/morefoe/morefoe_5.ogg", "halo_reach/dialog/combat/grunt1/01_contact/morefoe/morefoe_6.ogg",
						"halo_reach/dialog/combat/grunt1/01_contact/morefoe/morefoe_7.ogg", "halo_reach/dialog/combat/grunt1/01_contact/morefoe/morefoe_8.ogg",
						"halo_reach/dialog/combat/grunt1/01_contact/morefoe/morefoe_9.ogg", "halo_reach/dialog/combat/grunt1/01_contact/morefoe/morefoe_10.ogg",
						"halo_reach/dialog/combat/grunt1/01_contact/morefoe/morefoe_11.ogg", "halo_reach/dialog/combat/grunt1/01_contact/morefoe/morefoe_12.ogg" },
["OnSurprise"] = { "halo_reach/dialog/combat/grunt1/01_contact/srprs/srprs_1.ogg", "halo_reach/dialog/combat/grunt1/01_contact/srprs/srprs_2.ogg",
					"halo_reach/dialog/combat/grunt1/01_contact/srprs/srprs_3.ogg", "halo_reach/dialog/combat/grunt1/01_contact/srprs/srprs_4.ogg",
					"halo_reach/dialog/combat/grunt1/01_contact/srprs/srprs_5.ogg", "halo_reach/dialog/combat/grunt1/01_contact/srprs/srprs_6.ogg",
					"halo_reach/dialog/combat/grunt1/01_contact/srprs/srprs_7.ogg", "halo_reach/dialog/combat/grunt1/01_contact/srprs/srprs_8.ogg",
					"halo_reach/dialog/combat/grunt1/01_contact/srprs/srprs_9.ogg", "halo_reach/dialog/combat/grunt1/01_contact/srprs/srprs_11.ogg",
					"halo_reach/dialog/combat/grunt1/01_contact/srprs/srprs_12.ogg", "halo_reach/dialog/combat/grunt1/01_contact/srprs/srprs_13.ogg",
					"halo_reach/dialog/combat/grunt1/01_contact/srprs/srprs_14.ogg", "halo_reach/dialog/combat/grunt1/01_contact/srprs/srprs_15.ogg",
					"halo_reach/dialog/combat/grunt1/01_contact/srprs/srprs_16.ogg", "halo_reach/dialog/combat/grunt1/01_contact/srprs/srprs_17.ogg" },
["OnInvestigate"] = { "halo_reach/dialog/combat/grunt1/05_search/invsgt/invsgt_1.ogg", "halo_reach/dialog/combat/grunt1/05_search/invsgt/invsgt_2.ogg",
			"halo_reach/dialog/combat/grunt1/05_search/invsgt/invsgt_3.ogg", "halo_reach/dialog/combat/grunt1/05_search/invsgt/invsgt_4.ogg",
			"halo_reach/dialog/combat/grunt1/05_search/invsgt/invsgt_5.ogg", "halo_reach/dialog/combat/grunt1/05_search/invsgt/invsgt_6.ogg",
			"halo_reach/dialog/combat/grunt1/05_search/invsgt/invsgt_7.ogg", "halo_reach/dialog/combat/grunt1/05_search/invsgt/invsgt_8.ogg" },
["OnInvestigateFail"] = { "halo_reach/dialog/combat/grunt1/05_search/invsgt_fail/invsgt_fail_1.ogg", "halo_reach/dialog/combat/grunt1/05_search/invsgt_fail/invsgt_fail_2.ogg",
			"halo_reach/dialog/combat/grunt1/05_search/invsgt_fail/invsgt_fail_3.ogg", "halo_reach/dialog/combat/grunt1/05_search/invsgt_fail/invsgt_fail_4.ogg",
			"halo_reach/dialog/combat/grunt1/05_search/invsgt_fail/invsgt_fail_5.ogg", "halo_reach/dialog/combat/grunt1/05_search/invsgt_fail/invsgt_fail_6.ogg",
			"halo_reach/dialog/combat/grunt1/05_search/invsgt_fail/invsgt_fail_7.ogg", "halo_reach/dialog/combat/grunt1/05_search/invsgt_fail/invsgt_fail_8.ogg",
			"halo_reach/dialog/combat/grunt1/05_search/invsgt_fail/invsgt_fail_9.ogg", "halo_reach/dialog/combat/grunt1/05_search/invsgt_fail/invsgt_fail_10.ogg" },
["OnLostContact"] = { "halo_reach/dialog/combat/grunt1/05_search/lst_cntct/lst_cntct_1.ogg", "halo_reach/dialog/combat/grunt1/05_search/lst_cntct/lst_cntct_2.ogg",
			"halo_reach/dialog/combat/grunt1/05_search/lst_cntct/lst_cntct_3.ogg", "halo_reach/dialog/combat/grunt1/05_search/lst_cntct/lst_cntct_4.ogg",
			"halo_reach/dialog/combat/grunt1/05_search/lst_cntct/lst_cntct_5.ogg", "halo_reach/dialog/combat/grunt1/05_search/lst_cntct/lst_cntct_6.ogg",
			"halo_reach/dialog/combat/grunt1/05_search/lst_cntct/lst_cntct_7.ogg", "halo_reach/dialog/combat/grunt1/05_search/lst_cntct/lst_cntct_8.ogg",
			"halo_reach/dialog/combat/grunt1/05_search/lst_cntct/lst_cntct_9.ogg", "halo_reach/dialog/combat/grunt1/05_search/lst_cntct/lst_cntct_10.ogg",
			"halo_reach/dialog/combat/grunt1/05_search/lst_cntct/lst_cntct_11.ogg" },
["OnAttack"] = { "halo_reach/dialog/combat/grunt1/02_combat/strk/strk_1.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk/strk_2.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk/strk_3.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk/strk_4.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk/strk_6.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk/strk_8.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk/strk_10.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk/strk_12.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk/strk_13.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk/strk_16.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk/strk_17.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk/strk_18.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk/strk_19.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk/strk_20.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk/strk_21.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk/strk_22.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk/strk_23.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk/strk_24.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk/strk_25.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk/strk_26.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk/strk_27.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk/strk_28.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk/strk_29.ogg" },
["OnBerserk"] = { "halo_reach/dialog/combat/grunt1/02_combat/brsrk/brsrk_1.ogg", "halo_reach/dialog/combat/grunt1/02_combat/brsrk/brsrk_2.ogg", 
				  "halo_reach/dialog/combat/grunt1/02_combat/brsrk/brsrk_3.ogg", "halo_reach/dialog/combat/grunt1/02_combat/brsrk/brsrk_4.ogg", 
				  "halo_reach/dialog/combat/grunt1/02_combat/brsrk/brsrk_5.ogg" },
["OnCharge"] = { "halo_reach/dialog/combat/grunt1/02_combat/charge/charge_1.ogg", "halo_reach/dialog/combat/grunt1/02_combat/charge/charge_2.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/charge/charge_3.ogg", "halo_reach/dialog/combat/grunt1/02_combat/charge/charge_4.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/charge/charge_5.ogg", "halo_reach/dialog/combat/grunt1/02_combat/charge/charge_6.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/charge/charge_7.ogg", "halo_reach/dialog/combat/grunt1/02_combat/charge/charge_8.ogg" },
["OnCower"] = { "halo_reach/dialog/combat/grunt1/02_combat/cower/cower_2.ogg", "halo_reach/dialog/combat/grunt1/02_combat/cower/cower_3.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/cower/cower_4.ogg", "halo_reach/dialog/combat/grunt1/02_combat/cower/cower_5.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/cower/cower_6.ogg", "halo_reach/dialog/combat/grunt1/02_combat/cower/cower_7.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/cower/cower_9.ogg", "halo_reach/dialog/combat/grunt1/02_combat/cower/cower_10.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/cower/cower_11.ogg", "halo_reach/dialog/combat/grunt1/02_combat/cower/cower_13.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/cower/cower_14.ogg", "halo_reach/dialog/combat/grunt1/02_combat/cower/cower_18.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/cower/cower_19.ogg" },
["OnDamagedFoe"] = { "halo_reach/dialog/combat/grunt1/02_combat/damaged_enemy/damaged_enemy_1.ogg", "halo_reach/dialog/combat/grunt1/02_combat/damaged_enemy/damaged_enemy_2.ogg",
					"halo_reach/dialog/combat/grunt1/02_combat/damaged_enemy/damaged_enemy_3.ogg", "halo_reach/dialog/combat/grunt1/02_combat/damaged_enemy/damaged_enemy_4.ogg",
					"halo_reach/dialog/combat/grunt1/02_combat/damaged_enemy/damaged_enemy_5.ogg", "halo_reach/dialog/combat/grunt1/02_combat/damaged_enemy/damaged_enemy_6.ogg",
					"halo_reach/dialog/combat/grunt1/02_combat/damaged_enemy/damaged_enemy_7.ogg", "halo_reach/dialog/combat/grunt1/02_combat/damaged_enemy/damaged_enemy_8.ogg",
					"halo_reach/dialog/combat/grunt1/02_combat/damaged_enemy/damaged_enemy_9.ogg", "halo_reach/dialog/combat/grunt1/02_combat/damaged_enemy/damaged_enemy_10.ogg",
					"halo_reach/dialog/combat/grunt1/02_combat/damaged_enemy/damaged_enemy_12.ogg", "halo_reach/dialog/combat/grunt1/02_combat/damaged_enemy/damaged_enemy_13.ogg",
					"halo_reach/dialog/combat/grunt1/02_combat/damaged_enemy/damaged_enemy_14.ogg" },
["OnFlee"] = { "halo_reach/dialog/combat/grunt1/02_combat/flee/flee_1.ogg", "halo_reach/dialog/combat/grunt1/02_combat/flee/flee_3.ogg", 
			"halo_reach/dialog/combat/grunt1/02_combat/flee/flee_6.ogg", "halo_reach/dialog/combat/grunt1/02_combat/flee/flee_7.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/flee/flee_8.ogg", "halo_reach/dialog/combat/grunt1/02_combat/flee/flee_11.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/flee/flee_13.ogg", "halo_reach/dialog/combat/grunt1/02_combat/flee/flee_14.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/flee/flee_16.ogg", "halo_reach/dialog/combat/grunt1/02_combat/flee/flee_18.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/flee/flee_20.ogg", "halo_reach/dialog/combat/grunt1/02_combat/flee/flee_21.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/flee/flee_22.ogg", "halo_reach/dialog/combat/grunt1/02_combat/flee/flee_23.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/flee/flee_24.ogg", "halo_reach/dialog/combat/grunt1/02_combat/flee/flee_25.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/flee/flee_26.ogg", "halo_reach/dialog/combat/grunt1/02_combat/flee/flee_27.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/flee/flee_28.ogg", "halo_reach/dialog/combat/grunt1/02_combat/flee/flee_29.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/flee/flee_30.ogg", "halo_reach/dialog/combat/grunt1/02_combat/flee/flee_31.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/flee/flee_32.ogg", "halo_reach/dialog/combat/grunt1/02_combat/flee/flee_34.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/flee/flee_35.ogg", "halo_reach/dialog/combat/grunt1/02_combat/flee/flee_36.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/flee/flee_37.ogg", "halo_reach/dialog/combat/grunt1/02_combat/flee/flee_38.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/flee/flee_39.ogg", "halo_reach/dialog/combat/grunt1/02_combat/flee/flee_41.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/flee/flee_42.ogg" },
["OnKamikaze"] = { "halo_reach/dialog/combat/grunt1/02_combat/kamikaze/kamikaze_10.ogg", "halo_reach/dialog/combat/grunt1/02_combat/kamikaze/kamikaze_11.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/kamikaze/kamikaze_12.ogg", "halo_reach/dialog/combat/grunt1/02_combat/kamikaze/kamikaze_13.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/kamikaze/kamikaze_14.ogg", "halo_reach/dialog/combat/grunt1/02_combat/kamikaze/kamikaze_15.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/kamikaze/kamikaze_16.ogg", "halo_reach/dialog/combat/grunt1/02_combat/kamikaze/kamikaze_17.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/kamikaze/kamikaze_18.ogg" },
["OnCover"] = { "halo_reach/dialog/combat/grunt1/02_combat/move_cvr/move_cvr_3.ogg", "halo_reach/dialog/combat/grunt1/02_combat/move_cvr/move_cvr_4.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/move_cvr/move_cvr_5.ogg", "halo_reach/dialog/combat/grunt1/02_combat/move_cvr/move_cvr_8.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/move_cvr/move_cvr_10.ogg", "halo_reach/dialog/combat/grunt1/02_combat/move_cvr/move_cvr_11.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/move_cvr/move_cvr_13.ogg", "halo_reach/dialog/combat/grunt1/02_combat/move_cvr/move_cvr_15.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/move_cvr/move_cvr_16.ogg", "halo_reach/dialog/combat/grunt1/02_combat/move_cvr/move_cvr_18.ogg" },
["OnReload"] = { "halo_reach/dialog/combat/grunt1/02_combat/reloading/reloading_1.ogg", "halo_reach/dialog/combat/grunt1/02_combat/reloading/reloading_2.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/reloading/reloading_3.ogg", "halo_reach/dialog/combat/grunt1/02_combat/reloading/reloading_4.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/reloading/reloading_6.ogg", "halo_reach/dialog/combat/grunt1/02_combat/reloading/reloading_9.ogg" },
["OnRetreat"] = { "halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_1.ogg", "halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_2.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_3.ogg", "halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_5.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_6.ogg", "halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_7.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_8.ogg", "halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_10.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_11.ogg", "halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_12.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_14.ogg", "halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_15.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_19.ogg", "halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_20.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_22.ogg", "halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_23.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_25.ogg", "halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_26.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_27.ogg", "halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_28.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_29.ogg", "halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_30.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_31.ogg", "halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_32.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_33.ogg", "halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_34.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_35.ogg", "halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_36.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_37.ogg", "halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_38.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_39.ogg", "halo_reach/dialog/combat/grunt1/02_combat/rtrt/rtrt_40.ogg" },
["OnGrenadeThrow"] = { "halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_1.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_2.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_3.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_4.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_5.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_6.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_7.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_9.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_13.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_14.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_15.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_16.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_17.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_18.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_19.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_20.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_21.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_22.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_23.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_24.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_25.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_26.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_27.ogg", "halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_28.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/strk_grnd/strk_grnd_30.ogg" },
["OnTaunt"] = { "halo_reach/dialog/combat/grunt1/02_combat/thrtn/thrtn_1.ogg", "halo_reach/dialog/combat/grunt1/02_combat/thrtn/thrtn_2.ogg",
		"halo_reach/dialog/combat/grunt1/02_combat/thrtn/thrtn_4.ogg", "halo_reach/dialog/combat/grunt1/02_combat/thrtn/thrtn_5.ogg",
		"halo_reach/dialog/combat/grunt1/02_combat/thrtn/thrtn_7.ogg", "halo_reach/dialog/combat/grunt1/02_combat/thrtn/thrtn_8.ogg",
		"halo_reach/dialog/combat/grunt1/02_combat/thrtn/thrtn_9.ogg", "halo_reach/dialog/combat/grunt1/02_combat/thrtn/thrtn_11.ogg",
		"halo_reach/dialog/combat/grunt1/02_combat/thrtn/thrtn_11.ogg", "halo_reach/dialog/combat/grunt1/02_combat/thrtn/thrtn_13.ogg",
		"halo_reach/dialog/combat/grunt1/02_combat/thrtn/thrtn_14.ogg", "halo_reach/dialog/combat/grunt1/02_combat/thrtn/thrtn_15.ogg",
		"halo_reach/dialog/combat/grunt1/02_combat/thrtn/thrtn_16.ogg", "halo_reach/dialog/combat/grunt1/02_combat/thrtn/thrtn_18.ogg" },
["OnVictory"] = { "halo_reach/dialog/combat/grunt1/10_exclaim/chr/chr_1.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/chr/chr_2.ogg",
		"halo_reach/dialog/combat/grunt1/10_exclaim/chr/chr_3.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/chr/chr_4.ogg",
		"halo_reach/dialog/combat/grunt1/10_exclaim/chr/chr_6.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/chr/chr_7.ogg",
		"halo_reach/dialog/combat/grunt1/10_exclaim/chr/chr_8.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/chr/chr_8.ogg",
		"halo_reach/dialog/combat/grunt1/10_exclaim/chr/chr_10.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/chr/chr_10.ogg",
		"halo_reach/dialog/combat/grunt1/10_exclaim/chr/chr_11.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/chr/chr_14.ogg",
		"halo_reach/dialog/combat/grunt1/10_exclaim/chr/chr_15.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/chr/chr_16.ogg",
		"halo_reach/dialog/combat/grunt1/10_exclaim/chr/chr_17.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/chr/chr_18.ogg",
		"halo_reach/dialog/combat/grunt1/10_exclaim/chr/chr_19.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/chr/chr_20.ogg" },
["OnKillPlayer"] = { "halo_reach/dialog/combat/grunt1/10_exclaim/chr_deadmc/chr_deadmc_1.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/chr_deadmc/chr_deadmc_3.ogg",
		"halo_reach/dialog/combat/grunt1/10_exclaim/chr_deadmc/chr_deadmc_4.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/chr_deadmc/chr_deadmc_5.ogg",
		"halo_reach/dialog/combat/grunt1/10_exclaim/chr_deadmc/chr_deadmc_6.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/chr_deadmc/chr_deadmc_7.ogg",
		"halo_reach/dialog/combat/grunt1/10_exclaim/chr_deadmc/chr_deadmc_8.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/chr_deadmc/chr_deadmc_10.ogg",
		"halo_reach/dialog/combat/grunt1/10_exclaim/chr_deadmc/chr_deadmc_11.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/chr_deadmc/chr_deadmc_12.ogg",
		"halo_reach/dialog/combat/grunt1/10_exclaim/chr_deadmc/chr_deadmc_13.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/chr_deadmc/chr_deadmc_14.ogg",
		"halo_reach/dialog/combat/grunt1/10_exclaim/chr_deadmc/chr_deadmc_15.ogg" },
["OnPanic"] = { "halo_reach/dialog/combat/grunt1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_1.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_2.ogg",
		"halo_reach/dialog/combat/grunt1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_3.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_3.ogg",
		"halo_reach/dialog/combat/grunt1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_5.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_6.ogg",
		"halo_reach/dialog/combat/grunt1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_7.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_8.ogg",
		"halo_reach/dialog/combat/grunt1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_9.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_10.ogg",
		"halo_reach/dialog/combat/grunt1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_11.ogg", "halo_reach/dialog/combat/grunt1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_12.ogg",
		"halo_reach/dialog/combat/grunt1/10_exclaim/panic_plsmgrnd/panic_plsmgrnd_13.ogg" },
["OnUnderAttack"] = { "halo_reach/dialog/combat/grunt1/02_combat/undr_fire/undr_fire_1.ogg", "halo_reach/dialog/combat/grunt1/02_combat/undr_fire/undr_fire_2.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/undr_fire/undr_fire_4.ogg", "halo_reach/dialog/combat/grunt1/02_combat/undr_fire/undr_fire_6.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/undr_fire/undr_fire_8.ogg", "halo_reach/dialog/combat/grunt1/02_combat/undr_fire/undr_fire_12.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/undr_fire/undr_fire_13.ogg", "halo_reach/dialog/combat/grunt1/02_combat/undr_fire/undr_fire_14.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/undr_fire/undr_fire_15.ogg", "halo_reach/dialog/combat/grunt1/02_combat/undr_fire/undr_fire_16.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/undr_fire/undr_fire_18.ogg", "halo_reach/dialog/combat/grunt1/02_combat/undr_fire/undr_fire_19.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/undr_fire/undr_fire_20.ogg", "halo_reach/dialog/combat/grunt1/02_combat/undr_fire/undr_fire_21.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/undr_fire/undr_fire_22.ogg", "halo_reach/dialog/combat/grunt1/02_combat/undr_fire/undr_fire_23.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/undr_fire/undr_fire_24.ogg", "halo_reach/dialog/combat/grunt1/02_combat/undr_fire/undr_fire_26.ogg",
				"halo_reach/dialog/combat/grunt1/02_combat/undr_fire/undr_fire_27.ogg" },
["OnWarnIncoming"] = { "halo_reach/dialog/combat/grunt1/02_combat/warn_incmn/warn_incmn_1.ogg", "halo_reach/dialog/combat/grunt1/02_combat/warn_incmn/warn_incmn_2.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/warn_incmn/warn_incmn_3.ogg", "halo_reach/dialog/combat/grunt1/02_combat/warn_incmn/warn_incmn_4.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/warn_incmn/warn_incmn_5.ogg", "halo_reach/dialog/combat/grunt1/02_combat/warn_incmn/warn_incmn_6.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/warn_incmn/warn_incmn_7.ogg", "halo_reach/dialog/combat/grunt1/02_combat/warn_incmn/warn_incmn_8.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/warn_incmn/warn_incmn_9.ogg", "halo_reach/dialog/combat/grunt1/02_combat/warn_incmn/warn_incmn_10.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/warn_incmn/warn_incmn_11.ogg", "halo_reach/dialog/combat/grunt1/02_combat/warn_incmn/warn_incmn_12.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/warn_incmn/warn_incmn_13.ogg", "halo_reach/dialog/combat/grunt1/02_combat/warn_incmn/warn_incmn_14.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/warn_incmn/warn_incmn_16.ogg", "halo_reach/dialog/combat/grunt1/02_combat/warn_incmn/warn_incmn_17.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/warn_incmn/warn_incmn_18.ogg", "halo_reach/dialog/combat/grunt1/02_combat/warn_incmn/warn_incmn_19.ogg",
			"halo_reach/dialog/combat/grunt1/02_combat/warn_incmn/warn_incmn_20.ogg" },
["OnDive"] = { "halo_reach/dialog/combat/grunt1/11_involuntary/dive/dive_1.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dive/dive_2.ogg",
			"halo_reach/dialog/combat/grunt1/11_involuntary/dive/dive_3.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dive/dive_4.ogg",
			"halo_reach/dialog/combat/grunt1/11_involuntary/dive/dive_5.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dive/dive_6.ogg",
			"halo_reach/dialog/combat/grunt1/11_involuntary/dive/dive_7.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dive/dive_8.ogg",
			"halo_reach/dialog/combat/grunt1/11_involuntary/dive/dive_9.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dive/dive_10.ogg" },
["OnDodge"] = { "halo_reach/dialog/combat/grunt1/11_involuntary/dodge/dodge_1.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dodge/dodge_3.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dodge/dodge_4.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dodge/dodge_5.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dodge/dodge_6.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dodge/dodge_7.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dodge/dodge_8.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dodge/dodge_8.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dodge/dodge_10.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dodge/dodge_11.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dodge/dodge_12.ogg" },
["OnDeath"] = { "halo_reach/dialog/combat/grunt1/11_involuntary/dth/dth_2.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dth/dth_3.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dth/dth_4.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dth/dth_5.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dth/dth_6.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dth/dth_7.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dth/dth_8.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dth/dth_9.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dth/dth_10.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dth/dth_11.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dth/dth_12.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dth/dth_13.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dth/dth_13.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dth/dth_15.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dth/dth_16.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dth/dth_17.ogg" },
["OnDeathPainful"] = { "halo_reach/dialog/combat/grunt1/11_involuntary/dth_mjr/dth_mjr_1.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dth_mjr/dth_mjr_2.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dth_mjr/dth_mjr_3.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dth_mjr/dth_mjr_4.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dth_mjr/dth_mjr_5.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dth_mjr/dth_mjr_6.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dth_mjr/dth_mjr_7.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dth_mjr/dth_mjr_8.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dth_mjr/dth_mjr_9.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dth_mjr/dth_mjr_10.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dth_mjr/dth_mjr_10.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dth_mjr/dth_mjr_11.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dth_mjr/dth_mjr_12.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dth_mjr/dth_mjr_13.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dth_mjr/dth_mjr_14.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dth_mjr/dth_mjr_14.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dth_mjr/dth_mjr_17.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dth_mjr/dth_mjr_18.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/dth_mjr/dth_mjr_19.ogg" },
["OnFallDeath"] = { "halo_reach/dialog/combat/grunt1/11_involuntary/dth_fall/dth_fall_1.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dth_fall/dth_fall_2.ogg",
			"halo_reach/dialog/combat/grunt1/11_involuntary/dth_fall/dth_fall_3.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dth_fall/dth_fall_4.ogg",
			"halo_reach/dialog/combat/grunt1/11_involuntary/dth_fall/dth_fall_5.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/dth_fall/dth_fall_6.ogg",
			"halo_reach/dialog/combat/grunt1/11_involuntary/dth_fall/dth_fall_7.ogg" },
["OnDeathThrown"] = { "halo_reach/dialog/combat/grunt1/11_involuntary/thrwn/thrwn_1.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/thrwn/thrwn_2.ogg",
			"halo_reach/dialog/combat/grunt1/11_involuntary/thrwn/thrwn_3.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/thrwn/thrwn_4.ogg",
			"halo_reach/dialog/combat/grunt1/11_involuntary/thrwn/thrwn_4.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/thrwn/thrwn_6.ogg",
			"halo_reach/dialog/combat/grunt1/11_involuntary/thrwn/thrwn_7.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/thrwn/thrwn_7.ogg",
			"halo_reach/dialog/combat/grunt1/11_involuntary/thrwn/thrwn_9.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/thrwn/thrwn_10.ogg",
			"halo_reach/dialog/combat/grunt1/11_involuntary/thrwn/thrwn_11.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/thrwn/thrwn_12.ogg",
			"halo_reach/dialog/combat/grunt1/11_involuntary/thrwn/thrwn_13.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/thrwn/thrwn_14.ogg",
			"halo_reach/dialog/combat/grunt1/11_involuntary/thrwn/thrwn_15.ogg" },
["OnFall"] = { "halo_reach/dialog/combat/grunt1/11_involuntary/fall/fall_1.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/fall/fall_2.ogg",
			"halo_reach/dialog/combat/grunt1/11_involuntary/fall/fall_3.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/fall/fall_4.ogg",
			"halo_reach/dialog/combat/grunt1/11_involuntary/fall/fall_5.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/fall/fall_6.ogg",
			"halo_reach/dialog/combat/grunt1/11_involuntary/fall/fall_6.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/fall/fall_7.ogg",
			"halo_reach/dialog/combat/grunt1/11_involuntary/fall/fall_8.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/fall/fall_9.ogg",
			"halo_reach/dialog/combat/grunt1/11_involuntary/fall/fall_10.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/fall/fall_10.ogg",
			"halo_reach/dialog/combat/grunt1/11_involuntary/fall/fall_12.ogg" },
["OnHurt"] = { "halo_reach/dialog/combat/grunt1/11_involuntary/pain/pain_1.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/pain/pain_2.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/pain/pain_3.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/pain/pain_4.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/pain/pain_5.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/pain/pain_6.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/pain/pain_7.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/pain/pain_8.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/pain/pain_9.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/pain/pain_10.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/pain/pain_10.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/pain/pain_11.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/pain/pain_12.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/pain/pain_13.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/pain/pain_14.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/pain/pain_15.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/pain/pain_16.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/pain/pain_18.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/pain/pain_19.ogg" },
["OnHurtLarge"] = { "halo_reach/dialog/combat/grunt1/11_involuntary/pain_mjr/pain_mjr_1.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/pain_mjr/pain_mjr_2.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/pain_mjr/pain_mjr_3.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/pain_mjr/pain_mjr_3.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/pain_mjr/pain_mjr_5.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/pain_mjr/pain_mjr_6.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/pain_mjr/pain_mjr_7.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/pain_mjr/pain_mjr_8.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/pain_mjr/pain_mjr_9.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/pain_mjr/pain_mjr_10.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/pain_mjr/pain_mjr_11.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/pain_mjr/pain_mjr_11.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/pain_mjr/pain_mjr_13.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/pain_mjr/pain_mjr_14.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/pain_mjr/pain_mjr_15.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/pain_mjr/pain_mjr_16.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/pain_mjr/pain_mjr_18.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/pain_mjr/pain_mjr_19.ogg",
		"halo_reach/dialog/combat/grunt1/11_involuntary/pain_mjr/pain_mjr_20.ogg", "halo_reach/dialog/combat/grunt1/11_involuntary/pain_mjr/pain_mjr_21.ogg" },
["OnStep"] = { "halo_reach/characters/footsteps/grunt/hard_surface/walk/walk1.ogg", "halo_reach/characters/footsteps/grunt/hard_surface/walk/walk2.ogg",
		"halo_reach/characters/footsteps/grunt/hard_surface/walk/walk3.ogg", "halo_reach/characters/footsteps/grunt/hard_surface/walk/walk4.ogg",
		"halo_reach/characters/footsteps/grunt/hard_surface/walk/walk5.ogg", "halo_reach/characters/footsteps/grunt/hard_surface/walk/walk6.ogg" },
["OnBackpackDestroy"] = { "halo_reach/characters/grunt/grunt_backpack_steam/grunt_backpack_steam1.ogg", "halo_reach/characters/grunt/grunt_backpack_steam/grunt_backpack_steam2.ogg",
				"halo_reach/characters/grunt/grunt_backpack_steam/grunt_backpack_steam3.ogg" },
["OnLand"] = { "halo_reach/characters/footsteps/grunt/hard_surface/jump/jump1.ogg", "halo_reach/characters/footsteps/grunt/hard_surface/jump/jump2.ogg",
			"halo_reach/characters/footsteps/grunt/hard_surface/jump/jump3.ogg", "halo_reach/characters/footsteps/grunt/hard_surface/jump/jump4.ogg",
			"halo_reach/characters/footsteps/grunt/hard_surface/jump/jump5.ogg", "halo_reach/characters/footsteps/grunt/hard_surface/jump/jump6.ogg" }
	}
}